Section "Module"
    Load "glamoregl"
EndSection
Section "ServerFlags"
    Option "AutoAddDevices" "false"
    Option "AutoEnableDevices" "false"
    Option "AutoAddGPU" "false"
    Option "DontVTSwitch" "true"
    Option "AllowMouseOpenFail" "true"
EndSection
Section "Device"
    Identifier "BrowserPane virtual V3D"
    Driver "bpane"
EndSection
Section "Monitor"
    Identifier "Virtual monitor"
EndSection
Section "Screen"
    Identifier "Virtual screen"
    Device "BrowserPane virtual V3D"
    Monitor "Virtual monitor"
    DefaultDepth 24
EndSection
Section "ServerLayout"
    Identifier "Headless single screen"
    Screen "Virtual screen"
EndSection
